added linelist creation tools
synthesizer-project/grid-generation pull request #64
Opened 2024-04-17 10:37 UTC by stephenmwilkins

Added cloudy input scripts and notebook for creating a standard and vacuum linelists. 

## Issue Type

- Bug
- Document
- Enhancement

## Checklist
- [ ] I have read the [CONTRIBUTING.md]()
- [ ] I have added docstrings to all methods
- [ ] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no pep8 errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2025-02-13 12:36 UTC, WillJRoper commented
Can you detail why this is done the way it is? i.e. 

- Why notebooks? 
- Where do the line lists fit into the current way things work?
- How does this effect the current workflow?

2025-02-13 13:11 UTC, stephenmwilkins commented
> Can you detail why this is done the way it is? i.e.
> 
> * Why notebooks?

Notebooks because that's what I originally used and it generates a some sanity check figures.

> * Where do the line lists fit into the current way things work?

The linelist created by this utility are already used in the photoionisation modelling. It's now more transparent where they came from.

> * How does this affect the current workflow?

It doesn't.

2025-02-13 13:35 UTC, WillJRoper commented
> It doesn't.
But now we have notebooks being run in the workflow don't we? Or are you including a bunch of subsets generated by the notebook that will be automatically picked up? 

I'm just trying to understand how this fits in. If it is something the user may need to run to get a grid of their own from some incident grid they've created then it needs to logically slot into the workflow somehow.

2025-02-13 14:42 UTC, WillJRoper commented
Ok, I'm with you now. I think it's probably ok where it is as long as we document this in the cloudy README.

2025-02-13 14:44 UTC, WillJRoper requested changes
All good, just that 1 comment for clarity in the README

2025-02-13 14:44 UTC, WillJRoper commented on src/synthesizer_grids/cloudy/create_linelist/README.md
> +In our photoionisation modelling we need to provide cloudy with a list of lines which we're interested in. Here we use the outputs from several `cloudy` runs - including both stars and AGN and range
If you can just make it clear here there is a default but this can be done explicitly with the procedure below then I think that covers it all.

2025-02-14 10:17 UTC, stephenmwilkins commented on src/synthesizer_grids/cloudy/create_linelist/README.md
> +In our photoionisation modelling we need to provide cloudy with a list of lines which we're interested in. Here we use the outputs from several `cloudy` runs - including both stars and AGN and range
Done.

2025-02-14 14:59 UTC, WillJRoper approved these changes

2025-02-14 14:59 UTC, merged