Improve blackhole installation
synthesizer-project/grid-generation pull request #78
Opened 2024-09-30 08:51 UTC by stephenmwilkins

## Issue Type

- Bug
- Document
- Enhancement

## Checklist
- [ ] I have read the [CONTRIBUTING.md]()
- [ ] I have added docstrings to all methods
- [ ] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no pep8 errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-09-30 09:01 UTC, WillJRoper requested changes
Really nice! Thanks for integrating the `GridFile`, one less headache to deal with in the future!

2024-09-30 09:01 UTC, WillJRoper commented on src/synthesizer_grids/incident/blackholes/README.md
> +For most purposes the 'relagn' model is probably not required since BH spins are either not available or sufficiently small to not make a difference. Instead we can use the AGNSED model described in
Spins will be a lot more available in the future ;)

2024-09-30 09:01 UTC, WillJRoper commented on src/synthesizer_grids/incident/blackholes/README.md
Can you include an example command line call for each type of grid within the README? e.g.

``` bash
python ... <args>
```

2024-09-30 09:02 UTC, WillJRoper commented on src/synthesizer_grids/incident/blackholes/install_agnsed.py
> +sys.path.append("RELAGN/src/python_version")
Just saw the paragraph in the PR description... what a pain 🙄. I agree it's worth us automating, just worth providing some high level instructions 🤷

2025-02-13 09:04 UTC, stephenmwilkins commented on src/synthesizer_grids/incident/blackholes/utils.py
> -def broken_power_law(x, edges, indices, norms=False, normalise=True):
Yes, you're probably correct, but for the sake of getting it finished (and not having to raise another PR on Synthesizer) can we just leave it here for now since I don't currently have a separate use case?

2025-02-13 09:38 UTC, stephenmwilkins commented on src/synthesizer_grids/incident/blackholes/utils.py
> -sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
This is no longer relevant since the functions in utils are now in GridIO.

2025-02-13 09:39 UTC, stephenmwilkins commented on src/synthesizer_grids/incident/blackholes/install_agnsed.py
> +sys.path.append("RELAGN/src/python_version")
In the README.md and doc string.

2025-02-13 09:40 UTC, stephenmwilkins commented on src/synthesizer_grids/incident/blackholes/install_agnsed.py
I'd rather not right now.

2025-02-13 09:49 UTC, WillJRoper commented on src/synthesizer_grids/incident/blackholes/install_agnsed.py
It needs to be done at some point. Why not now? Are you expecting me to come in and do it? 😅

2025-02-13 09:55 UTC, stephenmwilkins commented on src/synthesizer_grids/incident/blackholes/README.md
Done

2025-02-13 10:40 UTC, WillJRoper approved these changes

2025-02-13 10:40 UTC, merged