added method to calculate bolometric luminosities of the grid
synthesizer-project/grid-generation pull request #80
Opened 2024-10-08 13:52 UTC by stephenmwilkins

## Issue Type

- Bug
- Document
- Enhancement

## Checklist
- [ ] I have read the [CONTRIBUTING.md]()
- [ ] I have added docstrings to all methods
- [ ] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no pep8 errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-10-08 14:03 UTC, WillJRoper commented on src/synthesizer_grids/grid_io.py
> +    def add_bolometric_luminosity(self):
To stop from having to call this individually in all scripts you could place a call to it after the spectra are written in `write_grid_common`

2025-02-14 15:01 UTC, WillJRoper requested changes
Just that comment (Q one) needs addressing then this can go. Still pretty sure you don't need that loop too.

2025-02-14 15:01 UTC, WillJRoper commented on src/synthesizer_grids/grid_io.py
> +        self.write_dataset(
This is something to think about though!

2025-02-14 15:13 UTC, stephenmwilkins commented on src/synthesizer_grids/grid_io.py
> +        self.write_dataset(
Within a single Grid I think there will only ever be a single bolometric luminosity, but I agree it's somewhat unique to an incident grid.

2025-02-14 15:27 UTC, stephenmwilkins commented on src/synthesizer_grids/grid_io.py
> +        for indices in tqdm(index_list):
Good point, I think I was copying the approach from calculating the ionising photon luminosities. Perhaps that was before the Sed object could hold multi-dimensional arrays?

2025-02-14 15:27 UTC, stephenmwilkins commented on src/synthesizer_grids/grid_io.py
> +        # Loop over grid points and calculate Q and store it
Fixed.

2025-02-14 16:19 UTC, WillJRoper commented on src/synthesizer_grids/grid_io.py
> +        for indices in tqdm(index_list):
Yea, I think that's all a relic from when the `Sed` didn't handle any of this properly. Even after it could store multidimensional arrays the bolometric integration couldn't handle >2D 😅

2025-02-14 16:21 UTC, WillJRoper commented on src/synthesizer_grids/grid_io.py
> +        self.write_dataset(
Could we signify that in some way? I'm not sure if it is that obvious, especially in the light that I did not realise that 😂

2025-03-04 11:10 UTC, closed without merging